/*
# Default request to our instance of Supabase

*/
GET {{SUPABASE_URL}}/rest/v1/
apikey: {{SUPABASE_ANON_KEY}}

HTTP/1.1 200  - OK
date: Wed, 31 May 2023 17:07:33 GMT
server: postgrest/10.1.2
content-type: application/openapi+json; charset=utf-8
content-profile: public
access-control-allow-origin: *
x-kong-upstream-latency: 23
x-kong-proxy-latency: 3
via: kong/2.8.1
connection: close
transfer-encoding: chunked
/*

*/
###
GET {{SUPABASE_URL}}/rest/v1/eotai_images
apikey: {{SUPABASE_ANON_KEY}}

HTTP/1.1 200  - OK
date: Wed, 31 May 2023 18:40:53 GMT
server: postgrest/10.1.2
content-type: application/json; charset=utf-8
content-range: 0-7/*
content-location: /eotai_images
content-profile: public
access-control-allow-origin: *
x-kong-upstream-latency: 3
x-kong-proxy-latency: 1
via: kong/2.8.1
connection: close
transfer-encoding: chunked
###
